### ISSUE TITLE
Pre-requisite checks for `ckcp/openshift_dev_setup.sh`

### ISSUE THREAD

**Issue by ramessesii2** [openshift-pipelines/pipelines-service#104]
## Tasks
1. Add a pre-requisite check function in the script to ensure that dependencies are satisfied.
2. Add appropriate error messages on failure of installation of resources for e.g.- [here](https://github.com/openshift-pipelines/pipelines-service/blob/main/ckcp/openshift_dev_setup.sh#L160)

**Comment by xinredhat** [comment]
fixed in PR #100

**Comment by ramessesii2** [comment]
Thanks @xinredhat, I'll close it then.
