### ISSUE TITLE
Possible discrepancy in path of files of gitops/ inside ./ckcp/run.sh

### ISSUE THREAD

**Issue by RAMESSESII2** [openshift-pipelines/pipelines-service#29]
* Getting a ```file doesn't exist error``` while running ```./ckcp/run.sh```.

### To recreate the error:
Do a ```./ckckp/run.sh``` 
![image](https://user-images.githubusercontent.com/54385449/157030582-160119ec-5032-4cb2-84a5-3c00f1f5ac5f.png)

### Possible fixes
- I can see this was due to [this]( https://github.com/openshift-pipelines/pipelines-service/commit/accbec9a906931347c6d9fd9afddebda6b72c2ac#diff-def424cd75610cfc9a3ab7d024938244ffc87a5a46ea39d4afbe84103624ddf8R26) from last commit only.
- Just changing that will do it.
@bnallapeta, or am I missing something while running run.sh.

**Comment by bnallapeta** [comment]
> * Getting a `file doesn't exist error` while running `./ckcp/run.sh`.
> 
> ### To recreate the error:
> Do a `./ckckp/run.sh` ![image](https://user-images.githubusercontent.com/54385449/157030582-160119ec-5032-4cb2-84a5-3c00f1f5ac5f.png)
> 
> ### Possible fixes
> * I can see this was due to [this](https://github.com/openshift-pipelines/pipelines-service/commit/accbec9a906931347c6d9fd9afddebda6b72c2ac#diff-def424cd75610cfc9a3ab7d024938244ffc87a5a46ea39d4afbe84103624ddf8R26) from last commit only.
> * Just changing that will do it.
>   @bnallapeta, or am I missing something while running run.sh.

@RAMESSESII2 Yes, I had actually commented this on the PR. Guess it was missed. Will fix this in the next PR.

**Comment by bnallapeta** [comment]
Fixed with https://github.com/openshift-pipelines/pipelines-service/pull/30
