### ISSUE TITLE
gsed is not a linux thing

### ISSUE THREAD

**Issue by matzew** [openshift-pipelines/pipelines-service#4]
For this https://github.com/openshift-pipelines/pipelines-service/blob/38556710979baefcd642d1a41f7649a7a6eb0eb0/run.sh#L138 I had to create a sym link to `sed` on my Fedora

**Comment by guillaumerose** [comment]
Oh yes sorry. I need to test it more regularly on Linux. gsed is GNU sed on macOS, not the BSD sed.

**Comment by guillaumerose** [comment]
gsed is gone now 👍
