### ISSUE TITLE
Make the necessary changes in the repo to conform to the short term architecture as drawn up in the pipelines service architecture doc

### ISSUE THREAD

**Issue by bnallapeta** [openshift-pipelines/pipelines-service#47]
https://docs.google.com/document/d/1iN-Uq9bcHme-STL7PCkkGiYAx5iqt9fhx8PJarwTjLA/edit#heading=h.ribbgykjijfk

This section describes the short term architecture for pipelines-service with kcp.

**Comment by fgiloux** [comment]
This is not a public document.
I have documented the architecture on the [readme](https://github.com/openshift-pipelines/pipelines-service#phase-1)

**Comment by bnallapeta** [comment]
Worked upon in #85 and #91
