### ISSUE TITLE
Provide base for pipeline configuration

### ISSUE THREAD

**Issue by fgiloux** [openshift-pipelines/pipelines-service#99]
In our base directory we should provide a base [TektonConfig](https://tekton.dev/docs/operator/tektonconfig/
) with guidance on common overlay configurations:
- pruning
- enabling feature gates like enable-tekton-oci-bundles, which we may want to enable per default

**Comment by bnallapeta** [comment]
@fgiloux TektonConfig is being provided as part of #122 for pruning purpose. Based on the description, you also wanted to provide other options such as feature flags. But that's specific for every customer right? Is the idea to actually enable them or just to document that it is possible to enable/disable?

**Comment by fgiloux** [comment]
@bnallapeta yes pruning will be addressed when #122 merges.
feature gates are a moving target, the normal lifecycle being that features are not activated by default in early stage, then gets activated by default and finally the feature gate is deprecated and removed when the feature is GA.
Regarding enable-tekton-oci-bundles it is [a feature we want to leverage in early stage](https://github.com/redhat-appstudio/infra-deployments/blob/941b81f5723ff1085706d3f759fd2c2e490ddcc1/components/build/openshift-pipelines/openshift-pipelines-feature-flags.yaml#L13). We should cover that in this or the next sprint.
The other aspect is yes we want to document and provide guidance for further customization.

**Comment by bnallapeta** [comment]
@fgiloux Thanks for the explanation. Let's plan for this in the upcoming sprint. Could you please create a Jira to track this?

**Comment by fgiloux** [comment]
closing this issue following #157
